version: '3.9'

services:
  db:
    image: postgres:13.3
    restart: unless-stopped
    environment:
      POSTGRES_DB: "ys-db"
      POSTGRES_USER: "ys-user"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5432:5432"